name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['16.x', '18.x']

    steps:
      - uses: actions/checkout@v1
      - name: use node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: pnpm/action-setup@v2
        with:
          run_install: true
      - name: npm run test, size and lint
        run: |
          npm run test
          npm run size
          npm run lint
